### ISSUE TITLE
MongoDB on a different server

### ISSUE THREAD

**Issue by mictadlo** [Uauy-Lab/expvip-web#44]
Hi,
In order to run MongoDB on a different server what is necessary to change?

Thank you in advance,

Michal

**Comment by homonecloco** [comment]
Hi, you need to setup the database in the ```mongoid.yml``` file. The project doesn't use Mongoid, but it reads the connecting databases from it.

**Comment by mictadlo** [comment]
Hi, 
Could you please provide an example of `mongoid.yml` file?

Thank you in advance,

Michal

**Comment by homonecloco** [comment]
The next release will by MySQL only, so this should simplify the setup.
