### ISSUE TITLE
Cloning expvip I got error of access denied, don't get the reason.

### ISSUE THREAD

**Issue by shahida110** [Uauy-Lab/expvip-web#66]
git clone https://github.com/Uauy-Lab/expvip-web
fatal: could not create work tree dir 'expvip-web': Permission denied

**Comment by homonecloco** [comment]
Hi, 
This is probably because you don't have write access on the directory where you are trying to clone the project.

**Comment by homonecloco** [comment]
I hope you managed to clone the project locally. Closing the issue due inactivity.
